% Script to process XML help files into HTML. This script can be invoked
% from the Matlab Start button (via the function qftm_helpup).
%
% Copyright ? 2008 Stephen J. Sangwine and Nicolas Le Bihan.
% See the file : Copyright.m for further details.

% TODO Better if L was constructed automatically by scanning the directory
% for files with extension xml.

L = {'abs'...
	 'bivector' 'bsxfun'...
     'cast' 'char' 'check_signature' 'clifford' 'clifford_conjugate' 'clifford_signature' 'conj'...
     'diag' 'disp' 'display' 'dual' 'dump'...
     'e' 'empty' 'eq' 'even'...
     'full'...
     'get_signature' 'grade' 'grade_four_involution' 'grade_involution'...
     'horzcat'...
     'inv' 'isempty' 'isexplicit' 'isreal'...
     'left_contraction' 'length' 'lu'...
     'mean' 'minus' 'mpower' 'mtimes'...
     'ndims' 'ne' 'normm' 'numel'...
     'odd'...
     'part' 'plus' 'power' 'pseudoscalar'...
     'rdivide' 'repmat' 'reshape' 'reverse' 'right_contraction'...
     'scalar' 'scalar_product' 'show' 'size' 'squeeze' 'subsasgn' 'subsref' 'sum'...
     'times' 'transpose' 'tril' 'triu' 'trivector'...
     'uminus' 'unit' 'uplus'...
     'vector' 'vertcat'...
     'wedge'...
     };

S = 'xmlfiles/cliffunction.xsl';

h = waitbar(0, 'Processing XML to HTML helpfiles ...');

N = length(L);

for i = 1:N
    F = L{i};
    waitbar(i/N, h)
    xslt(['xmlfiles/', F, '.xml'], S, [F, '.html']);
end
close(h)

% $Id: process.m 132 2017-05-17 16:53:51Z sangwine $
